name: Seed last_reviewed

on:
  workflow_dispatch:

jobs:
  seed-last-reviewed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install python-frontmatter GitPython

      - name: Run `add_last_reviewed.py`
        run: python scripts/add_last_reviewed.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # only commit if there were changes
          git diff --quiet || git commit -m "chore: seed last_reviewed in markdown" && git push
