name: Seed last_reviewed

# allow this workflow to push back to the repo
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  seed-last-reviewed:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout with full history & credentials so we can both read commit dates and push
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # grab entire history
          persist-credentials: true  # keep GITHUB_TOKEN for pushing

      # 2) set up Python...
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-frontmatter GitPython

      # 3) run your script
      - name: Seed last_reviewed
        run: python scripts/add_last_reviewed.py

      # 4) commit & push any changes
      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # test for staged changes; if there are any, commit & push
          if ! git diff --staged --quiet; then
            git commit -m "chore: seed last_reviewed in markdown"
            git push
          else
            echo "No changes to commit."
          fi
